version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./package.json:/app/package.json