global:
  scrape_interval: 5s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "k6"
    static_configs:
      - targets: ["k6:6565"]
    scrape_interval: 5s
    metrics_path: /metrics
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
